//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace a
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applications
    {
        public int Id { get; set; }
        public string PersonalFileNumber { get; set; }
        public System.DateTime SubmissionDate { get; set; }
        public System.TimeSpan SubmissionTime { get; set; }
        public int ApplicantId { get; set; }
        public string SelectedSpecialties { get; set; }
        public string Passport { get; set; }
        public string EducationDiploma { get; set; }
        public int Points { get; set; }
    
        public virtual Applicants Applicants { get; set; }
    }
}
