//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace a
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specialities
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public int AvailablePlaces { get; set; }
        public string EducationForm { get; set; }
        public decimal TuitionFee { get; set; }
    }
}
